/**
 * Real, independently-sourced historical Kp/ap data — NOT generated by
 * DRAKON's own pipeline. Used to validate the NOAA parser + Kp -> ap
 * conversion (plan §6.4, §21 Stage 1's "compare the generated ap series
 * against independent references") against real ground truth, not just
 * hand-picked unit-test points.
 *
 * Source: CelesTrak's CSSI Space Weather Data file (SW-All.txt), format
 * documented at https://celestrak.org/SpaceData/SpaceWx-format.php. This
 * file republishes GFZ Potsdam's official *definitive* Kp/ap index — a
 * fully independent product from the NOAA SWPC real-time "estimated Kp"
 * feed DRAKON actually ingests in production (see the estimatedAp naming
 * note on NoaaKpSample/ThreeHourApObservation in ../geomagneticIndex.ts).
 * Retrieved 2026-08-25 via the test fixtures bundled with the
 * st-bender/pyspaceweather GitHub repository, which vendors this same
 * CelesTrak file verbatim (SPDX: CC BY 4.0 per GFZ Potsdam's license on
 * the underlying index data).
 *
 * Kp is encoded in the source file as Kp*10 on the standard third-step
 * grid (e.g. 87 = Kp 8.67 = canonical class "9-"); kpNumeric below is
 * that value divided by 10, ready to feed into normalizeKpClass()/
 * kpToAp() directly. officialAp is the source's own published Ap column
 * for that interval — cross-checked by hand against KP_TO_AP_TABLE for
 * several rows before building this fixture (e.g. kpRawTenths=90 ->
 * kpNumeric=9.0 -> class "9o" -> table value 400, matching the source's
 * officialAp=400 for that interval).
 *
 * Covers 2024-05-07 through 2024-05-14 UTC (64 three-hour intervals):
 * a quiet lead-up, the extreme peak of the "Gannon storm" on 2024-05-11
 * (Kp reached 9o / ap 400 — the strongest geomagnetic storm since October
 * 2003), and the multi-day recovery. Chosen specifically to exercise both
 * quiet-condition and extreme-storm-condition agreement, not just an
 * arbitrary date range.
 */

export type GfzHistoricalKpApEntry = {
  /** Start of the three-hour UTC interval this row covers. */
  intervalStart: string;
  /** Raw Kp*10 value exactly as published in the source file. */
  kpRawTenths: number;
  /** kpRawTenths / 10 — DRAKON's numeric Kp grid representation. */
  kpNumeric: number;
  /** The source's own published ap for this interval — treated as ground truth here. */
  officialAp: number;
};

export const GFZ_HISTORICAL_KP_AP_MAY_2024: GfzHistoricalKpApEntry[] = [
  { intervalStart: '2024-05-07T00:00:00.000Z', kpRawTenths: 13, kpNumeric: 1.3, officialAp: 5 },
  { intervalStart: '2024-05-07T03:00:00.000Z', kpRawTenths: 13, kpNumeric: 1.3, officialAp: 5 },
  { intervalStart: '2024-05-07T06:00:00.000Z', kpRawTenths: 10, kpNumeric: 1.0, officialAp: 4 },
  { intervalStart: '2024-05-07T09:00:00.000Z', kpRawTenths: 13, kpNumeric: 1.3, officialAp: 5 },
  { intervalStart: '2024-05-07T12:00:00.000Z', kpRawTenths: 20, kpNumeric: 2.0, officialAp: 7 },
  { intervalStart: '2024-05-07T15:00:00.000Z', kpRawTenths: 27, kpNumeric: 2.7, officialAp: 12 },
  { intervalStart: '2024-05-07T18:00:00.000Z', kpRawTenths: 13, kpNumeric: 1.3, officialAp: 5 },
  { intervalStart: '2024-05-07T21:00:00.000Z', kpRawTenths: 13, kpNumeric: 1.3, officialAp: 5 },
  { intervalStart: '2024-05-08T00:00:00.000Z', kpRawTenths: 10, kpNumeric: 1.0, officialAp: 4 },
  { intervalStart: '2024-05-08T03:00:00.000Z', kpRawTenths: 17, kpNumeric: 1.7, officialAp: 6 },
  { intervalStart: '2024-05-08T06:00:00.000Z', kpRawTenths: 17, kpNumeric: 1.7, officialAp: 6 },
  { intervalStart: '2024-05-08T09:00:00.000Z', kpRawTenths: 17, kpNumeric: 1.7, officialAp: 6 },
  { intervalStart: '2024-05-08T12:00:00.000Z', kpRawTenths: 17, kpNumeric: 1.7, officialAp: 6 },
  { intervalStart: '2024-05-08T15:00:00.000Z', kpRawTenths: 20, kpNumeric: 2.0, officialAp: 7 },
  { intervalStart: '2024-05-08T18:00:00.000Z', kpRawTenths: 7, kpNumeric: 0.7, officialAp: 3 },
  { intervalStart: '2024-05-08T21:00:00.000Z', kpRawTenths: 10, kpNumeric: 1.0, officialAp: 4 },
  { intervalStart: '2024-05-09T00:00:00.000Z', kpRawTenths: 7, kpNumeric: 0.7, officialAp: 3 },
  { intervalStart: '2024-05-09T03:00:00.000Z', kpRawTenths: 13, kpNumeric: 1.3, officialAp: 5 },
  { intervalStart: '2024-05-09T06:00:00.000Z', kpRawTenths: 7, kpNumeric: 0.7, officialAp: 3 },
  { intervalStart: '2024-05-09T09:00:00.000Z', kpRawTenths: 13, kpNumeric: 1.3, officialAp: 5 },
  { intervalStart: '2024-05-09T12:00:00.000Z', kpRawTenths: 10, kpNumeric: 1.0, officialAp: 4 },
  { intervalStart: '2024-05-09T15:00:00.000Z', kpRawTenths: 10, kpNumeric: 1.0, officialAp: 4 },
  { intervalStart: '2024-05-09T18:00:00.000Z', kpRawTenths: 23, kpNumeric: 2.3, officialAp: 9 },
  { intervalStart: '2024-05-09T21:00:00.000Z', kpRawTenths: 20, kpNumeric: 2.0, officialAp: 7 },
  { intervalStart: '2024-05-10T00:00:00.000Z', kpRawTenths: 27, kpNumeric: 2.7, officialAp: 12 },
  { intervalStart: '2024-05-10T03:00:00.000Z', kpRawTenths: 27, kpNumeric: 2.7, officialAp: 12 },
  { intervalStart: '2024-05-10T06:00:00.000Z', kpRawTenths: 23, kpNumeric: 2.3, officialAp: 9 },
  { intervalStart: '2024-05-10T09:00:00.000Z', kpRawTenths: 20, kpNumeric: 2.0, officialAp: 7 },
  { intervalStart: '2024-05-10T12:00:00.000Z', kpRawTenths: 37, kpNumeric: 3.7, officialAp: 22 },
  { intervalStart: '2024-05-10T15:00:00.000Z', kpRawTenths: 77, kpNumeric: 7.7, officialAp: 179 },
  { intervalStart: '2024-05-10T18:00:00.000Z', kpRawTenths: 87, kpNumeric: 8.7, officialAp: 300 },
  { intervalStart: '2024-05-10T21:00:00.000Z', kpRawTenths: 87, kpNumeric: 8.7, officialAp: 300 },
  { intervalStart: '2024-05-11T00:00:00.000Z', kpRawTenths: 90, kpNumeric: 9.0, officialAp: 400 },
  { intervalStart: '2024-05-11T03:00:00.000Z', kpRawTenths: 83, kpNumeric: 8.3, officialAp: 236 },
  { intervalStart: '2024-05-11T06:00:00.000Z', kpRawTenths: 83, kpNumeric: 8.3, officialAp: 236 },
  { intervalStart: '2024-05-11T09:00:00.000Z', kpRawTenths: 90, kpNumeric: 9.0, officialAp: 400 },
  { intervalStart: '2024-05-11T12:00:00.000Z', kpRawTenths: 87, kpNumeric: 8.7, officialAp: 300 },
  { intervalStart: '2024-05-11T15:00:00.000Z', kpRawTenths: 83, kpNumeric: 8.3, officialAp: 236 },
  { intervalStart: '2024-05-11T18:00:00.000Z', kpRawTenths: 77, kpNumeric: 7.7, officialAp: 179 },
  { intervalStart: '2024-05-11T21:00:00.000Z', kpRawTenths: 77, kpNumeric: 7.7, officialAp: 179 },
  { intervalStart: '2024-05-12T00:00:00.000Z', kpRawTenths: 63, kpNumeric: 6.3, officialAp: 94 },
  { intervalStart: '2024-05-12T03:00:00.000Z', kpRawTenths: 70, kpNumeric: 7.0, officialAp: 132 },
  { intervalStart: '2024-05-12T06:00:00.000Z', kpRawTenths: 37, kpNumeric: 3.7, officialAp: 22 },
  { intervalStart: '2024-05-12T09:00:00.000Z', kpRawTenths: 43, kpNumeric: 4.3, officialAp: 32 },
  { intervalStart: '2024-05-12T12:00:00.000Z', kpRawTenths: 20, kpNumeric: 2.0, officialAp: 7 },
  { intervalStart: '2024-05-12T15:00:00.000Z', kpRawTenths: 30, kpNumeric: 3.0, officialAp: 15 },
  { intervalStart: '2024-05-12T18:00:00.000Z', kpRawTenths: 40, kpNumeric: 4.0, officialAp: 27 },
  { intervalStart: '2024-05-12T21:00:00.000Z', kpRawTenths: 63, kpNumeric: 6.3, officialAp: 94 },
  { intervalStart: '2024-05-13T00:00:00.000Z', kpRawTenths: 53, kpNumeric: 5.3, officialAp: 56 },
  { intervalStart: '2024-05-13T03:00:00.000Z', kpRawTenths: 60, kpNumeric: 6.0, officialAp: 80 },
  { intervalStart: '2024-05-13T06:00:00.000Z', kpRawTenths: 33, kpNumeric: 3.3, officialAp: 18 },
  { intervalStart: '2024-05-13T09:00:00.000Z', kpRawTenths: 27, kpNumeric: 2.7, officialAp: 12 },
  { intervalStart: '2024-05-13T12:00:00.000Z', kpRawTenths: 33, kpNumeric: 3.3, officialAp: 18 },
  { intervalStart: '2024-05-13T15:00:00.000Z', kpRawTenths: 27, kpNumeric: 2.7, officialAp: 12 },
  { intervalStart: '2024-05-13T18:00:00.000Z', kpRawTenths: 23, kpNumeric: 2.3, officialAp: 9 },
  { intervalStart: '2024-05-13T21:00:00.000Z', kpRawTenths: 23, kpNumeric: 2.3, officialAp: 9 },
  { intervalStart: '2024-05-14T00:00:00.000Z', kpRawTenths: 13, kpNumeric: 1.3, officialAp: 5 },
  { intervalStart: '2024-05-14T03:00:00.000Z', kpRawTenths: 13, kpNumeric: 1.3, officialAp: 5 },
  { intervalStart: '2024-05-14T06:00:00.000Z', kpRawTenths: 13, kpNumeric: 1.3, officialAp: 5 },
  { intervalStart: '2024-05-14T09:00:00.000Z', kpRawTenths: 23, kpNumeric: 2.3, officialAp: 9 },
  { intervalStart: '2024-05-14T12:00:00.000Z', kpRawTenths: 23, kpNumeric: 2.3, officialAp: 9 },
  { intervalStart: '2024-05-14T15:00:00.000Z', kpRawTenths: 17, kpNumeric: 1.7, officialAp: 6 },
  { intervalStart: '2024-05-14T18:00:00.000Z', kpRawTenths: 20, kpNumeric: 2.0, officialAp: 7 },
  { intervalStart: '2024-05-14T21:00:00.000Z', kpRawTenths: 7, kpNumeric: 0.7, officialAp: 3 },
];
